Repository wecode-bootcamp-korea/38-2nd-GoodPlace-frontend, pull requests merged in 2022-11, with the labels that each got.

#3 [38기 모유진] Footer
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#1 [38기 최현] NAV UI
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#2 [38기 김솔] Modal
  src/components/Modal/Modal.js
Labels: 멘토 리뷰 요청

#4 [38기 최현] Sign In / Sign Up 구현
  .gitignore
  package-lock.json
  package.json
  public/data/agreement.json
  public/data/nickname.json
  public/images/kakao_login_large_narrow.png
  src/Router.js
  src/components/Modal/LoginModal.js
  src/components/Nav/Nav.js
  src/index.js
  src/pages/SignIn/KakaoLogin.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/AgreementList.jsx
  src/pages/SignUp/NICKNAMES.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/UserInfo.jsx
  src/pages/context/LoginContext.js
Labels: 멘토 리뷰 요청

#7 [38기 최현] NAV - HOTFIX
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#8 [38기 김솔] Review Tab
  src/pages/ProductDetail/MenuTab/ReviewTab/Review.jsx
  src/pages/ProductDetail/MenuTab/ReviewTab/StarRate.jsx
Labels: 멘토 리뷰 요청

#5 [38기 김솔] List Page
  .gitignore
  package-lock.json
  package.json
  public/images/MapMarkerIcon/brandcolormarker.png
  public/index.html
  src/Router.js
  src/components/Modal/Modal.js
  src/config.js
  src/pages/ProductList/CATEGORIES.js
  src/pages/ProductList/Filter/Calendar.jsx
  src/pages/ProductList/Filter/DetailedFilter.jsx
  src/pages/ProductList/Filter/Filter.jsx
  src/pages/ProductList/Header/CategoryBox.jsx
  src/pages/ProductList/Header/Header.jsx
  src/pages/ProductList/Header/SettingLocation.jsx
  src/pages/ProductList/List/List.jsx
  src/pages/ProductList/List/MapContainer.jsx
  src/pages/ProductList/List/MapMarkerWrap.jsx
  src/pages/ProductList/List/PremiumCard.jsx
  src/pages/ProductList/List/ProductCard.jsx
  src/pages/ProductList/ProductList.js
Labels: 완료

#13 [38기 모유진] Footer
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#11 [38기 모유진] SignIn UI
  src/pages/SignIn/SignIn.js
Labels: 멘토 리뷰 요청

#9 [38기 최현] Review Comments 레이아웃
  src/pages/ProductDetail/MenuTab/ReviewTab/ReviewComments.jsx
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#15 [38기 최현] Book Page LAYOUT
  public/data/bookagreement.json
  src/Router.js
  src/pages/Book/Book.js
  src/pages/Book/CheckList.jsx
Labels: 멘토 리뷰 요청

#16 [38기 김솔] Review Tab
  package-lock.json
  package.json
  src/Router.js
  src/components/Modal/Modal.js
  src/config.js
  src/pages/ProductDetail/MenuTab/ReviewTab/BigImage.jsx
  src/pages/ProductDetail/MenuTab/ReviewTab/Review.jsx
  src/pages/ProductDetail/MenuTab/ReviewTab/ReviewComments.jsx
  src/pages/ProductDetail/MenuTab/ReviewTab/ReviewForm.jsx
  src/pages/ProductDetail/MenuTab/ReviewTab/StarRate.jsx
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#6 [38기 모유진] BookList
  public/data/bookData.json
  public/data/bookDetailData.json
  src/Router.js
  src/pages/BookList/BookList.js
  src/pages/BookList/BookListDetail.js
  src/pages/BookList/BookListHeader.js
Labels: Conflict 해결 요청, 수정 요청, 추가 기능 구현 중

#14 [38기 김솔] FIX : List Page
  src/pages/ProductList/Filter/Calendar.jsx
  src/pages/ProductList/List/List.jsx
  src/pages/ProductList/List/PremiumCard.jsx
  src/pages/ProductList/List/ProductCard.jsx
  src/pages/ProductList/ProductList.js
Labels: 완료

#10 [38기 최현] ADD : 상세페이지 구현 완료 ( 리뷰 제외 )
  package-lock.json
  package.json
  src/config.js
  src/pages/ProductDetail/Carousel/Carousel.js
  src/pages/ProductDetail/Carousel/SwiperSlide.css
  src/pages/ProductDetail/Carousel/SwiperSlide.jsx
  src/pages/ProductDetail/Info/Info.jsx
  src/pages/ProductDetail/MenuTab/BookTab/BookTab.js
  src/pages/ProductDetail/MenuTab/BookTab/Calendar.jsx
  src/pages/ProductDetail/MenuTab/BookTab/RoomItem.jsx
  src/pages/ProductDetail/MenuTab/BookTab/RoomList.jsx
  src/pages/ProductDetail/MenuTab/BookTab/RoomSwiper.css
  src/pages/ProductDetail/MenuTab/BookTab/RoomSwiper.jsx
  src/pages/ProductDetail/MenuTab/InfoTab/Basic.jsx
  src/pages/ProductDetail/MenuTab/InfoTab/Host.jsx
  src/pages/ProductDetail/MenuTab/InfoTab/InfoTab.js
  src/pages/ProductDetail/MenuTab/InfoTab/Time.jsx
  src/pages/ProductDetail/MenuTab/MenuTab.js
  src/pages/ProductDetail/MenuTab/ReviewTab/Review.jsx
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#18 [38기 최현] Api/config
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/BookList/BookList.js
  src/pages/BookList/BookListDetail.js
  src/pages/Main/Main.js
  src/pages/ProductDetail/MenuTab/BookTab/RoomItem.jsx
  src/pages/ProductDetail/MenuTab/BookTab/RoomList.jsx
  src/pages/ProductDetail/ProductDetail.js
  src/pages/SignIn/KakaoLogin.js
  src/pages/SignUp/UserInfo.jsx
Labels: 완료
